/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mitali;

/**
 *
 * @author Mitali Sahoo
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        but5 = new javax.swing.JButton();
        std = new javax.swing.JLabel();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        but9 = new javax.swing.JButton();
        but10 = new javax.swing.JButton();
        but11 = new javax.swing.JButton();
        but12 = new javax.swing.JButton();
        but13 = new javax.swing.JButton();
        but14 = new javax.swing.JButton();
        but15 = new javax.swing.JButton();
        but16 = new javax.swing.JButton();
        but17 = new javax.swing.JButton();
        but18 = new javax.swing.JButton();
        but19 = new javax.swing.JButton();
        but20 = new javax.swing.JButton();
        but21 = new javax.swing.JButton();
        but22 = new javax.swing.JButton();
        but23 = new javax.swing.JButton();
        but24 = new javax.swing.JButton();
        but25 = new javax.swing.JButton();
        txt2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();

        but5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but5.setText("but1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        std.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        std.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        std.setText("Standard");

        but1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but1.setText("%");
        but1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });

        but2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but2.setText("CE");
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });

        but3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but3.setText("7");
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });

        but4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but4.setText("4");
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });

        but6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but6.setText("1");
        but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but6ActionPerformed(evt);
            }
        });

        but7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but7.setText("+/-");
        but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but7ActionPerformed(evt);
            }
        });

        but8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but8.setText("0");
        but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but8ActionPerformed(evt);
            }
        });

        but9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but9.setText("2");
        but9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but9ActionPerformed(evt);
            }
        });

        but10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but10.setText("5");
        but10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but10ActionPerformed(evt);
            }
        });

        but11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but11.setText("8");
        but11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but11ActionPerformed(evt);
            }
        });

        but12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but12.setText("C");
        but12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but12ActionPerformed(evt);
            }
        });

        but13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but13.setText("√");
        but13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        but13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but13ActionPerformed(evt);
            }
        });

        but14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but14.setText("x2");
        but14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        but14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but14ActionPerformed(evt);
            }
        });

        but15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but15.setText("Back");
        but15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but15ActionPerformed(evt);
            }
        });

        but16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but16.setText("9");
        but16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but16ActionPerformed(evt);
            }
        });

        but17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but17.setText("6");
        but17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but17ActionPerformed(evt);
            }
        });

        but18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but18.setText(".");
        but18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but18ActionPerformed(evt);
            }
        });

        but19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but19.setText("3");
        but19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but19ActionPerformed(evt);
            }
        });

        but20.setBackground(new java.awt.Color(102, 204, 255));
        but20.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but20.setText("=");
        but20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        but20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but20ActionPerformed(evt);
            }
        });

        but21.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but21.setText("+");
        but21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        but21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but21ActionPerformed(evt);
            }
        });

        but22.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but22.setText("-");
        but22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        but22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but22ActionPerformed(evt);
            }
        });

        but23.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but23.setText("*");
        but23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        but23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but23ActionPerformed(evt);
            }
        });

        but24.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but24.setText("/");
        but24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        but24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but24ActionPerformed(evt);
            }
        });

        but25.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        but25.setText("1/x");
        but25.setAutoscrolls(true);
        but25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        but25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but25ActionPerformed(evt);
            }
        });

        txt2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(153, 153, 153));
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txt1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(std, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(but7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(but10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(but18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(but22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(but13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(but12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(but14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(but11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(but16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(but15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(but24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but23, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                            .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(std, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but25, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but19, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but13ActionPerformed
       
    }//GEN-LAST:event_but13ActionPerformed

    private void but21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but21ActionPerformed
        String s=txt1.getText();
        double num=Double.parseDouble(s);
        txt2.setText(s+" + ");
        txt1.setText("");
    }//GEN-LAST:event_but21ActionPerformed

    private void but20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but20ActionPerformed
        String s=txt2.getText();
        double num=0;
        String s3="";
        int i=0;
        double res;
        while(s.charAt(i)!=' ')
        {   s3+=s.charAt(i);
            i++;
        }
        num=Double.parseDouble(s3);
        i++;
        char op=s.charAt(i);
        String s2=txt1.getText();
        double num2=Double.parseDouble(s2);
        switch(op)
        {
            case '+':
                    res=num+num2;
                    txt2.setText(Double.toString(res));
                    break;
            case '-':
                    res=num-num2;
                    txt2.setText(Double.toString(res));
                    break;
            case '*':
                    res=num*num2;
                    txt2.setText(Double.toString(res));
                    break;
            case '/':
                    double res1=(double)num/num2;
                    txt2.setText(Double.toString(res1));
                    break;
        }
    }//GEN-LAST:event_but20ActionPerformed

    private void but22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but22ActionPerformed
        String s=txt1.getText();
        double num=Double.parseDouble(s);
        
        txt2.setText(s+" - ");
        txt1.setText("");
    }//GEN-LAST:event_but22ActionPerformed

    private void but23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but23ActionPerformed
        
        String s=txt1.getText();
        
            double num=Double.parseDouble(s);
            txt2.setText(s+" * ");
            txt1.setText("");
        
    }//GEN-LAST:event_but23ActionPerformed

    private void but24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but24ActionPerformed
        String s=txt1.getText();
        double num=Double.parseDouble(s);
        txt2.setText(s+" / ");
        txt1.setText("");
    }//GEN-LAST:event_but24ActionPerformed

    private void but14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but14ActionPerformed
        String s=txt1.getText();
        double num=Double.parseDouble(s);
        double sqnum=num*num;
        txt2.setText(Double.toString(sqnum));
        
    }//GEN-LAST:event_but14ActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
        
        String s=txt2.getText();
        double num=0;
        String s3="";
        int i=0;
        while(s.charAt(i)!=' ')
        {   ++i;
            s3+=s.charAt(i);
        }
        num=Double.parseDouble(s3);
        i++;
        char op=s.charAt(i);
        if(op=='*')
        {
            String s2=txt1.getText();
            double num2=Double.parseDouble(s2);
            double res=num+(num*num2/100.0);
            txt2.setText(Double.toString(res));
        }
    }//GEN-LAST:event_but1ActionPerformed

    private void but25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but25ActionPerformed
        String s=txt1.getText();
        double num=Double.parseDouble(s);
        double rev=1.0/num;
        txt2.setText(rev+"");
    }//GEN-LAST:event_but25ActionPerformed

    private void but12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but12ActionPerformed
        txt1.setText("");
        txt2.setText("");
    }//GEN-LAST:event_but12ActionPerformed

    private void but15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but15ActionPerformed
        String s=txt1.getText();
        String newS="";
        int i=0;
        int len=s.length();
        newS=s.substring(0,len-1);
        txt1.setText(newS);
    }//GEN-LAST:event_but15ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
        txt2.setText("");
    }//GEN-LAST:event_but2ActionPerformed

    private void but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but7ActionPerformed
        String s=txt1.getText();
        double num=Double.parseDouble(s);
        if(num>0)
        {
            num=0-num;
        }
        else
        {
            num=-num;
        }
        txt1.setText(num+"");
        txt2.setText(num+"");
    }//GEN-LAST:event_but7ActionPerformed

    private void but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6ActionPerformed
        txt1.setText(txt1.getText()+"1");
    }//GEN-LAST:event_but6ActionPerformed

    private void but9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but9ActionPerformed
        txt1.setText(txt1.getText()+"2");
    }//GEN-LAST:event_but9ActionPerformed

    private void but19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but19ActionPerformed
        txt1.setText(txt1.getText()+"3");
    }//GEN-LAST:event_but19ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
        txt1.setText(txt1.getText()+"4");
    }//GEN-LAST:event_but4ActionPerformed

    private void but10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but10ActionPerformed
        txt1.setText(txt1.getText()+"5");
    }//GEN-LAST:event_but10ActionPerformed

    private void but17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but17ActionPerformed
        txt1.setText(txt1.getText()+"6");
    }//GEN-LAST:event_but17ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
        txt1.setText(txt1.getText()+"7");
    }//GEN-LAST:event_but3ActionPerformed

    private void but11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but11ActionPerformed
        txt1.setText(txt1.getText()+"8");
    }//GEN-LAST:event_but11ActionPerformed

    private void but16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but16ActionPerformed
        txt1.setText(txt1.getText()+"9");
    }//GEN-LAST:event_but16ActionPerformed

    private void but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but8ActionPerformed
        txt1.setText(txt1.getText()+"0");
    }//GEN-LAST:event_but8ActionPerformed

    private void but18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but18ActionPerformed
        txt1.setText(txt1.getText()+".");
        
    }//GEN-LAST:event_but18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JButton but10;
    private javax.swing.JButton but11;
    private javax.swing.JButton but12;
    private javax.swing.JButton but13;
    private javax.swing.JButton but14;
    private javax.swing.JButton but15;
    private javax.swing.JButton but16;
    private javax.swing.JButton but17;
    private javax.swing.JButton but18;
    private javax.swing.JButton but19;
    private javax.swing.JButton but2;
    private javax.swing.JButton but20;
    private javax.swing.JButton but21;
    private javax.swing.JButton but22;
    private javax.swing.JButton but23;
    private javax.swing.JButton but24;
    private javax.swing.JButton but25;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton but9;
    private javax.swing.JLabel std;
    private javax.swing.JTextField txt1;
    private javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables
}
